#!/bin/sh

# install additional software packages using apt (keep it at minimum)
sudo apt update && \
	sudo apt install exa bat ripgrep stow -y

# stow the config file from dotfiles into the container
cd ~/dotfiles
rm -rf .git

stow -t ~/ nvim

rm ~/.zshrc
cp -v zsh/.zshrc ~/.zshrc.bak
stow -t ~/ zsh

# install fzf manually (throws error when installed through binary)
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --key-bindings --completion --no-update-rc --no-bash --no-fish
echo "export FZF_HOME=~/.fzf" >> ~/.zshrc
echo "export PATH=\$FZF_HOME/bin:\$PATH" >> ~/.zshrc
echo "[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh \n" >> ~/.zshrc

# switch to zsh
echo "zsh" >> ~/.bashrc
