[tools]

neovim = "latest"
ripgrep = "latest"
lsd = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
starship = "latest"
node = "latest"
chezmoi = "latest"
ruff = "latest"
go = "latest"
python = "latest"
ruby = "latest"

"ubi:fluxcd/flux2" = { version = "latest", exe = "flux" }
